server:
  port: 8888

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
  expiration: 86400

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:https://jo-config-service-918490e97d40.herokuapp.com/}
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000  # 5 seconds
        response-timeout: 30000 # 30 seconds
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - JwtTokenFilterFactory

        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**
            - Path=/offertypes/**
            - Path=/prices/**
          filters:
            - JwtTokenFilterFactory

        - id: key-generator-service
          uri: lb://KEY-GENERATOR-SERVICE
          predicates:
            - Path=/key-generator/**
          filters:
            - JwtTokenFilterFactory

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
          filters:
            - JwtTokenFilterFactory

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filters:
            - JwtTokenFilterFactory

        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/tickets/**
          filters:
            - JwtTokenFilterFactory

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - JwtTokenFilterFactory

        - id: venue-service
          uri: lb://VENUE-SERVICE
          predicates:
            - Path=/venues/**
            - Path=/locations/**
          filters:
            - JwtTokenFilterFactory

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

    discovery:
      client:
        serviceUrl:
          defaultZone: https://jo-discovery-service-24208bfc4a7a.herokuapp.com/eureka
